### ISSUE TITLE
There is a potential bug in the latest version

### ISSUE THREAD

**Issue by cuishuang** [shima-park/agollo#35]
![image](https://user-images.githubusercontent.com/15921519/80436517-e7962100-8931-11ea-915f-49c93e81d2ae.png)

When I use v1.1.10,everything is okay; But when I re-init go module,the execute `go mod tidy` to get the package. I get v1.1.12, but this version cat not read the config info

 
![image](https://user-images.githubusercontent.com/15921519/80436755-7014c180-8932-11ea-94a7-d073c38d269d.png)

**Comment by shima-park** [comment]
Thanks for your feedback, I will check it, when I have time.

**Comment by shima-park** [comment]
Can you give me more information about this error?
I guess your situation may be caused by changes in v1.1.11.  [issue](https://github.com/shima-park/agollo/issues/30)
In this version, I removed the default loading “application” namespace. The user must explicitly pass the namespace that needs to be loaded.
```
	if len(options.PreloadNamespaces) == 0 {
		options.PreloadNamespaces = []string{defaultNamespace}
	} else {
		if !stringInSlice(defaultNamespace, options.PreloadNamespaces) {
			PreloadNamespaces(defaultNamespace)(&options)
		}
	}
```

There are three suggestions.
1. Use old version of SDK.
2. Use new version of SDK, And a little code modification to explicitly pass the namespace.
```
// use agollo.PreloadNamespaces option
a, err := agollo.New("localhost:8080", "your_appid",
		agollo.PreloadNamespaces("application", ...),
		// other options...
	)
```
or 

```
// use agollo.AutoFetchOnCacheMiss option
a, err := agollo.New("localhost:8080", "your_appid",
		agollo.AutoFetchOnCacheMiss(),
		// other options...
	)
```

**Comment by cuishuang** [comment]
ok !  I use 1.10 and all was stable.
If you need some infomation, feel free to add my wechat:  cuimoman

Thanks again for your kind help
